### ISSUE TITLE
catfile() bug when protocol in dirname (url)

### ISSUE THREAD

**Issue by ginzel** [ingydotnet/io-all-pm#50]
Hello,

try please
```
use IO::All;
my(%opt) = (
        url             => 'ftp://my_host.local/',
        remote_dir      => 'directory',
        file_name       => 'file.txt',
);
warn "IO::All::VERSION = $IO::All::VERSION";
warn io->catfile(@opt{qw/url remote_dir file_name/});
```
It returns
```
IO::All::VERSION = 0.67 at io_all_catfilebug.pl line 9.
ftp:/my_host.local/directory/file.txt at io_all_catfilebug.pl line 10.
```
instaed of `ftp://my_host.local/directory/file.txt` – the slash after protocol is missing.

Regards
HG

**Comment by estrabd** [comment]
This is an artifact of how File:Spec works:

    use File::Spec;
    my(%opt) = (
        url             => 'ftp://my_host.local/',
        remote_dir      => 'directory',
        file_name       => 'file.txt',
    );
    warn File::Spec->catfile(@opt{qw/url remote_dir file_name/});

Returns:

    ftp:/my_host.local/directory/file.txt at test.pl line 7.

**Comment by wchristian** [comment]
@ginzel I think @estrabd is correct here. You're trying to build a URL, but you're using path manipulating tools for that. This is especially incorrect, as you'll get wildly different fresults from catfile, depending on what OS you're on. That catfile can sometimes be used successfully to build URLs on unix is merely an accident.

@frew, @ingydotnet : I think this can be closed, unless maybe you want to add some code that recognizes such accidental misuses and warns/dies upon them?

**Comment by frew** [comment]
I know nothing about this project. Wrong frew?

**Comment by wchristian** [comment]
@frew: Oops, yes, sorry. I meant @frioux. :)

**Comment by frioux** [comment]
lol, arg it's my nemesis @frew who got my username *after* me because when I signed up it was 5 chars or more!

@wchristian I agree; closing unless @ingydotnet thinks it should work.

**Comment by ginzel** [comment]
In that case, add please a "safe" function for concatenating url parts, let say io->concat[enate].
@frioux, @ingydotnet  please reopen the issue.

**Comment by frioux** [comment]
reopened, though I don't think concat is nearly obvious enough.  Maybe url_concat though.

**Comment by estrabd** [comment]
Why not just create a new issue. This issue was closed because it was a non-issue on IO::All's part. What I am reading above from @ginzel sounds like a feature request.

**Comment by frioux** [comment]
Agreed. @ginzel, create an issue that describes what you want please.

-- 
sent from a rotary phone, pardon my brevity
